- name: Install NodeJS
  hosts: all
  tasks:
    - name: Update the cache
      shell: 'sudo apt update'
    - name: Install node and npm
      shell: 'apt install nodejs npm'
    - name: Confirm nodejs version
      shell: 'node -v'
