- name: Install NodeJS
  hosts: all
  tasks:
    - name: Update the cache
      shell: 'apt update'
    - name: Install curl
      shell: 'apt install curl'
    - name: Download nodejs
      shell: 'curl -sL https://deb.nodesource.com/setup_16.x | bash -'
    - name: Install nodejs
      shell: 'apt install nodejs'
