apiVersion: apps/v1
kind: Deployment
metadata:
  name: devopsg3-k8s-deployment
  labels:
    app: devopsg3-k8s
spec:
  replicas: 2
  selector:
    matchLabels:
      app: devopsg3-k8s
  template:
    metadata:
      labels:
        app: devopsg3-k8s
    spec:
      containers:
        - name: devopsg3-k8s
          image: hawksdev/devops3-k8s:latest
          ports:
            - containerPort: 3000
          env:
            - name: NODE_ENV
              valueFrom:
                configMapKeyRef:
                  name: devopsg3-k8s-config-map
                  key: NODE_ENV
            - name: MONGODB_URL
              valueFrom:
                secretKeyRef:
                  name: devopsg3-k8s-secret
                  key: MONGODB_URL
